# Generated by Django 3.1 on 2020-08-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarterbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=32)),
                ('position', models.CharField(default='Null', max_length=2)),
                ('Passing_yards', models.IntegerField(default=0)),
                ('Passing_TD', models.IntegerField(default=0)),
                ('INT', models.IntegerField(default=0)),
                ('Rush_yrds', models.IntegerField(default=0)),
                ('Rush_TD', models.IntegerField(default=0)),
                ('FPTS', models.IntegerField(default=0)),
                ('Projected_Passing_yards', models.IntegerField(default=0)),
                ('Projected_Passing_TD', models.IntegerField(default=0)),
                ('Projected_INT', models.IntegerField(default=0)),
                ('Projected_Rush_yrds', models.IntegerField(default=0)),
                ('Projected_Rush_TD', models.IntegerField(default=0)),
                ('Projected_FPTS', models.IntegerField(default=0)),
                ('Projected_OUTLOOK', models.TextField(default='None')),
            ],
        ),
    ]
