# Generated by Django 3.1 on 2020-08-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200822_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterbacks',
            old_name='Projected_Rush_yrds',
            new_name='Projected_Rush_yards',
        ),
        migrations.RenameField(
            model_name='quarterbacks',
            old_name='Rush_yrds',
            new_name='Rush_yards',
        ),
    ]
