# Generated by Django 3.1 on 2020-08-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200822_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quarterbacks',
            new_name='Quarterback',
        ),
    ]
