# Generated by Django 3.1 on 2020-08-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200822_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterback',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='position',
            field=models.TextField(),
        ),
    ]
