# Generated by Django 3.1 on 2020-08-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200822_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterback',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='quarterback',
            old_name='position',
            new_name='Position',
        ),
    ]
