# Generated by Django 3.1 on 2020-08-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200822_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterback',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quarterback',
            name='Position',
            field=models.CharField(max_length=10),
        ),
    ]
