# Generated by Django 3.1 on 2020-08-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200822_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterback',
            old_name='Projected_Rush_yards',
            new_name='Projected_Rush_Yards',
        ),
        migrations.RenameField(
            model_name='quarterback',
            old_name='Rush_yards',
            new_name='Rush_Yards',
        ),
    ]
