# Generated by Django 3.1 on 2020-08-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200822_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterback',
            old_name='player_name',
            new_name='Player_Name',
        ),
        migrations.RenameField(
            model_name='quarterback',
            old_name='player_position',
            new_name='Player_Position',
        ),
    ]
