# Generated by Django 3.1 on 2020-08-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200822_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterback',
            old_name='Player_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quarterback',
            old_name='Player_Position',
            new_name='position',
        ),
    ]
