# Generated by Django 3.1 on 2020-08-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200822_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterback',
            old_name='position',
            new_name='pos',
        ),
    ]
