# Generated by Django 3.1 on 2020-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20200822_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterback',
            name='pos',
            field=models.CharField(max_length=3),
        ),
    ]
