# Generated by Django 3.1 on 2020-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_quarterback_bye_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runningback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=3)),
                ('Bye_Week', models.CharField(default=0, max_length=10)),
                ('rush_yards', models.IntegerField(default=0)),
                ('rush_td', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('rec_yards', models.IntegerField(default=0)),
                ('rec_td', models.IntegerField(default=0)),
                ('total_yards', models.IntegerField(default=0)),
                ('total_td', models.IntegerField(default=0)),
                ('fpts', models.FloatField(default=0)),
                ('Projected_rush_yards', models.IntegerField(default=0)),
                ('Projected_rush_td', models.IntegerField(default=0)),
                ('Projected_receptions', models.IntegerField(default=0)),
                ('Projected_rec_yards', models.IntegerField(default=0)),
                ('Projected_rec_td', models.IntegerField(default=0)),
                ('projected_total_yards', models.IntegerField(default=0)),
                ('projected_total_td', models.IntegerField(default=0)),
                ('Projected_fpts', models.FloatField(default=0)),
                ('Projected_OUTLOOK', models.TextField(default='None')),
            ],
        ),
    ]
