# Generated by Django 3.1 on 2020-08-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20200823_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningback',
            old_name='Bye_Week',
            new_name='bye_week',
        ),
    ]
