# Generated by Django 3.1 on 2020-08-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_widereceiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widereceiver',
            name='projected_catch_percentage',
        ),
    ]
