# Generated by Django 3.1 on 2020-08-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_remove_widereceiver_catch_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tightend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=3)),
                ('bye_week', models.CharField(default=0, max_length=10)),
                ('targets', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('rec_yards', models.IntegerField(default=0)),
                ('rec_td', models.IntegerField(default=0)),
                ('fpts', models.FloatField(default=0)),
                ('projected_targets', models.IntegerField(default=0)),
                ('projected_receptions', models.IntegerField(default=0)),
                ('projected_rec_yards', models.IntegerField(default=0)),
                ('projected_rec_td', models.IntegerField(default=0)),
                ('projected_fpts', models.FloatField(default=0)),
                ('projected_OUTLOOK', models.TextField(default='None')),
            ],
        ),
    ]
