# Generated by Django 3.1 on 2020-08-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_tightend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=32)),
                ('bye_week', models.CharField(max_length=10)),
                ('sacks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField()),
                ('td', models.IntegerField()),
                ('fpts', models.IntegerField()),
                ('projected_sacks', models.IntegerField()),
                ('projected_turnovers', models.IntegerField()),
                ('projected_td', models.IntegerField()),
                ('projected_fpts', models.IntegerField()),
                ('projected_OUTLOOK', models.TextField(default='None')),
            ],
        ),
    ]
