# Generated by Django 3.1 on 2020-08-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_defense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=3)),
                ('bye_week', models.CharField(default=0, max_length=10)),
                ('total_made_fg', models.IntegerField(default=0)),
                ('fpts', models.IntegerField()),
                ('projected_total_made_fg', models.IntegerField(default=0)),
                ('projected_fpts', models.IntegerField(default=0)),
                ('projected_OUTLOOK', models.TextField(default=None)),
            ],
        ),
    ]
