# Generated by Django 3.1 on 2020-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_kicker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicker',
            name='fpts',
            field=models.IntegerField(default=0),
        ),
    ]
