# Generated by Django 3.1 on 2020-08-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_fantasyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=3)),
                ('bye_week', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
