# Generated by Django 3.1 on 2020-08-27 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.fantasyuser')),
            ],
        ),
    ]
