# Generated by Django 3.1 on 2020-08-27 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0031_auto_20200826_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FantasyUser',
        ),
    ]
