# Generated by Django 3.1 on 2020-09-02 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0032_auto_20200826_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_drafted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
    ]
